### ISSUE TITLE
Remove force unwrap in line 70 in Trackingplan.swift

### ISSUE THREAD

**Issue by d4nielRV** [trackingplan/trackingplan-ios#2]
Please avoid that kind of force unwrap since it could trigger in a crash for the app.
For example here
https://github.com/trackingplan/trackingplan-ios/blob/8fd2fa441dd9a971d0ff0b2df5b48702ed0b58ab/Sources/Trackingplan/Trackingplan.swift#L70

I know you're assigning a default value to the parameter in the initialize method, 

`customDomains: Dictionary <String, String>? = [:]`

but actually if I pass a `nil` instead of removing the parameter, the app will crash. For example you can test the code added below:

`Trackingplan.initialize(tpId: "XXXXXX", customDomains: nil)`

**Comment by kozkozkoz** [comment]
Thanks, updated :) Very helpful!
